# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Scan By Black Duck
      run: |
        bash <(curl -s -L https://detect.synopsys.com/detect.sh) --blackduck.url=https://poc39.blackduck.synopsys.com --blackduck.api.token=YTRhNGQ4ZDItZjMwYi00YzgwLWJkMmQtOTE4MDg4Y2I2ZjM0OmJjNTk2MGEwLTJmNmItNDQ3OS1hMDhlLWY4Nzg1OWVkNTdmZQ== --detect.project.version.name=1.0  --detect.project.name=XXX --blackduck.trust.cert=true

